"""HTML exporter — generates a self-contained timeline visualization of traces."""

from pathlib import Path

from agenttrace.span import Span, SpanTree

_HTML_TPL = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>AgentTrace — {trace_name}</title>
<style>
  {{"{{"}}
    * {{ box-sizing: border-box; margin: 0; padding: 0; }}
    body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; background: #0d1117; color: #c9d1d9; padding: 24px; }}
    h1 {{ font-size: 1.6em; margin-bottom: 4px; }}
    .subtitle {{ color: #8b949e; margin-bottom: 24px; }}
    .summary {{ display: flex; gap: 32px; padding: 16px 24px; background: #161b22; border-radius: 8px; border: 1px solid #30363d; margin-bottom: 24px; }}
    .stat {{ }}
    .stat-label {{ font-size: 0.75em; color: #8b949e; text-transform: uppercase; letter-spacing: 0.05em; }}
    .stat-value {{ font-size: 1.3em; font-weight: 700; }}

    .timeline {{ position: relative; padding: 20px 0; }}
    .timeline-bar {{ position: relative; height: 32px; margin: 2px 0; border-radius: 4px; display: flex; align-items: center; padding-left: 8px; font-size: 0.8em; white-space: nowrap; overflow: hidden; cursor: pointer; transition: opacity 0.2s; min-width: 4px; }}
    .timeline-bar:hover {{ opacity: 0.85; }}
    .bar-agent {{ background: #1f6feb; }}
    .bar-llm {{ background: #238636; }}
    .bar-tool {{ background: #9e6a03; }}
    .bar-thought {{ background: #8957e5; }}
    .bar-label {{ position: absolute; left: 8px; color: white; text-shadow: 0 1px 2px rgba(0,0,0,0.5); overflow: hidden; text-overflow: ellipsis; max-width: 300px; pointer-events: none; }}
    .bar-duration {{ position: absolute; right: 8px; color: rgba(255,255,255,0.7); font-size: 0.85em; pointer-events: none; }}

    .details {{ margin-top: 24px; }}
    .detail-card {{ background: #161b22; border: 1px solid #30363d; border-radius: 8px; margin-bottom: 8px; overflow: hidden; }}
    .detail-header {{ padding: 12px 16px; cursor: pointer; display: flex; justify-content: space-between; align-items: center; user-select: none; }}
    .detail-header:hover {{ background: #1c2128; }}
    .detail-body {{ padding: 12px 16px; border-top: 1px solid #30363d; display: none; font-size: 0.9em; line-height: 1.5; }}
    .detail-body.open {{ display: block; }}
    .detail-body pre {{ background: #0d1117; padding: 12px; border-radius: 4px; overflow-x: auto; margin-top: 8px; }}
    .tag {{ display: inline-block; padding: 2px 8px; border-radius: 4px; font-size: 0.75em; margin: 0 2px; }}
    .tag-agent {{ background: #1f6feb33; color: #58a6ff; }}
    .tag-llm {{ background: #23863633; color: #3fb950; }}
    .tag-tool {{ background: #9e6a0333; color: #d29922; }}
    .tag-thought {{ background: #8957e533; color: #a371f7; }}
    .footer {{ margin-top: 32px; font-size: 0.8em; color: #8b949e; text-align: center; }}
  }}
</style>
</head>
<body>
  <h1>Agent Trace: {trace_name}</h1>
  <p class="subtitle">{span_count} spans · generated by AgentTrace v0.1.0</p>

  <div class="summary">
    <div class="stat"><div class="stat-label">Duration</div><div class="stat-value">{total_duration:.0f} ms</div></div>
    <div class="stat"><div class="stat-label">Spans</div><div class="stat-value">{span_count}</div></div>
    <div class="stat"><div class="stat-label">Tokens</div><div class="stat-value">{total_tokens}</div></div>
    <div class="stat"><div class="stat-label">Cost</div><div class="stat-value">${total_cost:.6f}</div></div>
  </div>

  <div class="timeline" style="padding-left: {indent}px;">
    {timeline_bars}
  </div>

  <div class="details">
    <h3 style="margin-bottom: 8px;">Span Details</h3>
    {detail_cards}
  </div>

  <div class="footer">Generated by AgentTrace v0.1.0</div>
  <script>
    document.querySelectorAll('.detail-header').forEach(h => {{
      h.addEventListener('click', () => {{
        h.nextElementSibling.classList.toggle('open');
      }});
    }});
  </script>
</body>
</html>
"""


class HtmlExporter:
    """Generates a standalone HTML timeline view of a trace.

    The output is a single self-contained HTML file with embedded styles.
    It uses a Gantt-chart-style timeline and collapsible detail cards.
    """

    def export(self, spans: list[Span], output_path: str | Path) -> Path:
        """Generate the HTML report and write it to *output_path*.

        Returns the path to the generated file.
        """
        tree = SpanTree(spans)
        root = tree.root
        if root is None:
            raise ValueError("No root span found in the trace data.")

        total_duration = root.duration_ms
        indent = 20 + tree.max_depth() * 20

        # Build timeline bars
        bars_html = ""
        tree_spans = tree.walk()
        for s in tree_spans:
            if s is root:
                continue
            depth = tree.depth_of(s.span_id)
            left_pct = ((s.start_time - root.start_time) / max(total_duration / 1000, 0.001)) * 100
            width_pct = max((s.duration_ms / max(total_duration, 0.001)) * 100, 1.0)
            bar_class = f"bar-{s.span_type}" if s.span_type in ("agent", "llm", "tool", "thought") else "bar-agent"

            bars_html += (
                f'<div class="timeline-bar {bar_class}" '
                f'style="margin-left: {depth * 20}px; width: {width_pct}%;">'
                f'<span class="bar-label">{s.name}</span>'
                f'<span class="bar-duration">{s.duration_ms:.0f}ms</span>'
                f'</div>\n'
            )

        # Build detail cards
        cards_html = ""
        for s in tree_spans:
            tag_class = f"tag-{s.span_type}"
            io_section = ""
            if s.input:
                io_section += f"<strong>Input:</strong><pre>{_escape(s.input[:500])}</pre>"
            if s.output:
                io_section += f"<strong>Output:</strong><pre>{_escape(s.output[:500])}</pre>"
            meta_str = "".join(
                f"<tr><td>{k}</td><td>{_escape(str(v)[:100])}</td></tr>"
                for k, v in s.metadata.items()
            )
            meta_table = f"<table>{meta_str}</table>" if meta_str else ""

            cards_html += (
                f'<div class="detail-card">'
                f'<div class="detail-header">'
                f'<span><span class="tag {tag_class}">{s.span_type}</span> '
                f'<strong>{s.name}</strong> ({s.span_id})</span>'
                f'<span>{s.duration_ms:.0f}ms · {s.token_count or 0} tok · ${s.cost_usd:.6f}</span>'
                f'</div>'
                f'<div class="detail-body">{io_section}{meta_table}</div>'
                f'</div>\n'
            )

        total_tokens = sum(s.token_count for s in spans)
        total_cost = sum(s.cost_usd for s in spans)
        trace_name = root.name

        html = _HTML_TPL.format(
            trace_name=trace_name,
            span_count=len(spans),
            total_duration=total_duration,
            total_tokens=total_tokens,
            total_cost=total_cost,
            indent=indent,
            timeline_bars=bars_html,
            detail_cards=cards_html,
        )

        output_path = Path(output_path)
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(html)
        return output_path


def _escape(text: str) -> str:
    """HTML-escape special characters."""
    return (
        text.replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace('"', "&quot;")
    )
